version: "3"
services:
  nginx:
    image: nginx
    volumes: 
      - /home/component/nginx/log:/var/log/nginx
      - /home/component/nginx/conf.d:/etc/nginx/conf.d
      - /home/component/nginx/html:/usr/share/nginx/html
      - /home/component/nginx/nginx.conf:/etc/nginx/nginx.conf  
    restart: always
    container_name:  nginx
    hostname: nginx
    privileged: true
    network_mode: "host"  
      
      #networks:
      #default:
      #driver: host      
